### ISSUE TITLE
Jumping to a definition should close the buffer and go back to the original

### ISSUE THREAD

**Issue by asmeurer** [tkf/emacs-jedi-direx#1]
Usually tools like this close the buffer and go back to the original when they close, but when you choose a definition, it just goes to it in the same new buffer that it created.

**Comment by tkf** [comment]
I think this can be fixed by combination with popwin.el.  See also: https://github.com/m2ym/direx-el#usage

**Comment by asmeurer** [comment]
Thanks, that works perfectly, and it also makes things work better in general with similar buffers like occur or compile.
