### ISSUE TITLE
Deferred AttributeError on launch

### ISSUE THREAD

**Issue by wecassidy** [tkf/emacs-jedi-direx#22]
When I start jedi-direx, i get the following error message: `deferred error : (error "\"AttributeError(\\\"module 'jedi.api' has no attribute 'defined_names'\\\",)\"")`

I'm using emacs-jedi-direx version 20140310.236 from MELPA, emacs-jedi version 20160425.2156 from MELPA, Python 3.6, and Jedi 0.11.1.

**Comment by immerrr** [comment]
@wecassidy please, update emacs-jedi to current master version, I believe it should be fixed with the recent changes.
