### ISSUE TITLE
Make this installable from MELPA

### ISSUE THREAD

**Issue by wyuenho** [tkf/emacs-jedi-direx#6]

**Comment by tkf** [comment]
Anyone can write recipe and send PR to MELPA, so feel free to do it before I get a chance to do it.

**Comment by proofit404** [comment]
@tkf Here is a recipe for jedi-direx on melpa: https://github.com/milkypostman/melpa/blob/master/recipes/jedi-direx
I think you can safely close this issue.

**Comment by tkf** [comment]
thanks
