### ISSUE TITLE
direx-jedi buffer is always empty

### ISSUE THREAD

**Issue by croshchupkin** [tkf/emacs-jedi-direx#8]
Hi. The issue is as follows: I open a .py file (bar.py, in my case), type an import, define some primitive functions, define an almost-empty class. Then I hit `C-c x` - and see the direx-jedi buffer that contains only the following: 
[-]_direx-jedi: bar.py_

When I hit `g` in the direx-jedi buffer, I get an error. See the attached image for details. 
My .emacs file: https://gist.github.com/croshchupkin/914fc79d465049e7909c

![jedi-direx-error](https://f.cloud.github.com/assets/1482288/804965/402e5910-ee1e-11e2-9fcb-21b694354ca3.png)

**Comment by tkf** [comment]
Can you reproduce it with `make tryout`?  See also: https://github.com/tkf/emacs-jedi/blob/master/CONTRIBUTING.md#bug-report--question

**Comment by feicunrain** [comment]
I also have this problem. Because jedi-direx is not available from ELPA. I git  clone it from here. and install direx from elpa.then get a empty buffer

**Comment by feicunrain** [comment]
BTW.I also install jedi from elpa

**Comment by karmadharma** [comment]
I have the same issue, installed jedi-direx and all the relevant dependencies from github (dependencies included, not using ELPA), started emacs with no init file, manually loaded only jedi-direx and in python files the buffer is always empty, and as in the above if I press 'g' I get the following:

apply: Wrong number of arguments: (lambda (item &key recursive) "Currently it always recursively refreshes whole tree." (if jedi-direx:item-refresh--recurring (call-next-method) (let\* ((jedi-direx:item-refresh--recurring t) (root (direx:item-root item)) (module (direx:item-tree root))) (if (save-current-buffer (set-buffer (eieio-oref module (quote :buffer))) (if (eq (cdr (eieio-oref module (quote :cache))) jedi:defined-names--cache) nil (eieio-oset module (quote :cache) (cons nil jedi:defined-names--cache)))) (call-next-method root :recursive t) (message "No need to refresh"))))), 1

**Comment by tacy** [comment]
I have same issue, my jedi info:

(:emacs-version "24.3.1" :jedi-version "0.1.3alpha2")
((:version "2.7.3 (default, Apr 10 2013, 06:20:15) \n[GCC 4.6.3]" :name "sys" :file nil)
 (:version "0.7.0" :name "jedi" :file "/home/tacy/.emacs.d/el-get/jedi/env/local/lib/python2.7/site-packages/jedi/**init**.pyc")
 (:version "0.0.5" :name "epc" :file "/home/tacy/.emacs.d/el-get/jedi/env/local/lib/python2.7/site-packages/epc/**init**.pyc")
 (:version "0.0.3" :name "sexpdata" :file "/home/tacy/.emacs.d/el-get/jedi/env/local/lib/python2.7/site-packages/sexpdata.pyc"))

I start jedkepcserver using '--log' , the log file can't seen request call

**Comment by deftpunk** [comment]
Same issue.  All dependencies install via elpa, git clone of jedi-direx, same jedi info as @tacy 

With the <code>make tryout</code> suggestion I assume that you mean run <code>make tryout</code> in the downloaded jedi directory:
<code>
    e@bob ~/./e/jedi-20130714.1415> make tryout
    make: **\* No rule to make target `Carton', needed by`elpa'.  Stop.
</code>

Didn't get very far.  I assume this is in part due to Carton becoming Cask(?).

**Comment by asyncmind0** [comment]
Same issue _bump_ please suggest a workaround/hack till it gets fixed 

(:emacs-version "24.3.1" :jedi-version "0.1.3alpha2")  
((:version "2.7.5 (default, Sep  6 2013, 09:55:21) \n[GCC 4.8.1 20130725 (prerelease)]" :name "sys" :file nil)  
 (:version "0.7.0" :name "jedi" :file "/home/steven/.local/lib/python2.7/site-packages/jedi/**init**.pyc")  
 (:version "0.0.5" :name "epc" :file "/home/steven/.local/lib/python2.7/site-packages/epc/**init**.pyc")  
 (:version "0.0.3" :name "sexpdata" :file "/home/steven/.local/lib/python2.7/site-packages/sexpdata.pyc"))

**Comment by josrom** [comment]
same problem:
Mark saved where search started
apply: Wrong number of arguments: #[(item &key recursive) "^H\203^G^@Å \207Æ^XÇ !^ZÈ
!^[rÉ^KÊ\"q\210É^KË\"A^L=?\205*^@Ì^KËÍ^LB#)\2036^@Å
ÎÆ#\2029^@ÏÐ!+\207" [jedi-direx:item-refresh--recurring item root module jedi:defined-names--cache call-next-method t direx:item-root direx:item-tree eieio-oref ...] 5 "Currently it alw\
ays recursively refreshes whole tree."], 1

all installed using melpa

**Comment by wiredfool** [comment]
+1

**Comment by tkf** [comment]
I think my PR #13 fixes it.  I'll pull it when I confirmed.
